In [1]:
import numpy as np
import tensorflow as tf

In [2]:
# 1. Convolve 
# https://www.tensorflow.org/api_docs/python/tf/nn/conv2d

# default data in "NHWC" oder- [batch, height, width, channels]
A = np.array([[4,9,4,5,6],[8,3,6,8,5],[6,8,1,9,0],[5,8,1,1,3]]).reshape((1,4,5,1)).astype("float32")
# filter / kernel shape [filter_height, filter_width, in_channels, out_channels]
B = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]]).reshape((3,3,1,1))

# stride in NHWC order
strides = [1,2,2,1]
# padding in "NHWC" oder- [[0, 0], [pad_top, pad_bottom],[pad_left, pad_right], [0, 0]]
padding = [[0, 0],[1, 1], [1, 1],[0, 0]]

C = tf.nn.conv2d(A, B, strides=strides, padding=padding, data_format='NHWC')
print('C= \n',C.numpy()[0,:,:,0])


C= 
 [[ -1.  -4.  14.]
 [  3. -20. -17.]]


In [3]:
# 2. Transposed Convolution/deconvolution 
# https://www.tensorflow.org/api_docs/python/tf/nn/conv2d_transpose

At = np.array([[9,4,5],[3,6,8],[8,1,9]]).reshape((1,3,3,1))
Bt = (np.array([[0,1,0],[1,4,1],[0,1,0]])/8).reshape((3,3,1,1))

output_shape = [5,5]
strides = [1,2,2,1]
padding = [[0, 0],[1, 1], [1, 1],[0, 0]]

D = tf.nn.conv2d_transpose(At, Bt, output_shape=output_shape, strides=strides, padding=padding, data_format='NHWC')
print('D= \n', D.numpy()[0,:,:,0])

D= 
 [[4.5   1.625 2.    1.125 2.5  ]
 [1.5   0.    1.25  0.    1.625]
 [1.5   1.125 3.    1.75  4.   ]
 [1.375 0.    0.875 0.    2.125]
 [4.    1.125 0.5   1.25  4.5  ]]
