In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score

# for easier reading np display only 3 fraction digits
np.set_printoptions(precision=3,suppress=True)

In [2]:
# Read data
from google.colab import drive
drive.mount("/content/drive")
with open('/content/drive/My Drive/Colab Notebooks/data/iris.csv', 'r') as f: 
  temp = np.genfromtxt(f,delimiter=',',skip_header=0)
X, y = temp[:, :-1], temp[:, -1]

Mounted at /content/drive


In [3]:
# (Optional) Information about data
label, labelCount = np.unique(y,return_counts=True)
print('num of classes:', len(label))
for i in range(len(label)):
  print('class %i has %i samples'%(label[i],labelCount[i]))
print('num of samples: ', X.shape[0])

num of classes: 3
class 1 has 50 samples
class 2 has 50 samples
class 3 has 50 samples
num of samples:  150


In [4]:
# check nan, data imputation
from sklearn.impute import KNNImputer
X1 = X  # a temporary variable holding all feature vectors 
if np.sum(np.isnan(X1)):
  print('Total of NaN before imputation:', np.sum(np.isnan(X1)))
  imputer = KNNImputer(n_neighbors=2, weights="uniform")
  X = imputer.fit_transform(X1)  # update X with imputed dataset
  print('Total of NaN after imputation:', np.sum(np.isnan(X1)))
else:
  print('no NaN')

no NaN


In [5]:
# Data Partitioning 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, shuffle = True, stratify = y);

print('training data size: ', X_train.shape[0])
print('testing data size: ', X_test.shape[0])

training data size:  120
testing data size:  30


In [6]:
# Model building:  KNN classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5).fit(X_train, y_train)
y_pred = knn.predict(X_test)


In [8]:
# Performance evaluation 
print("P(classification) =", np.round(accuracy_score(y_test, y_pred), 3))
print("Confusion matrix: \n", confusion_matrix(y_test, y_pred))


P(classification) = 0.967
Confusion matrix: 
 [[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
