Load iris.csv, split it into training/testing at 80/20 ratio

In [23]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [24]:
import numpy  as np
import pandas as pd
import matplotlib.pyplot as plt
# from sklearn.preprocessing import OneHotEncoder

tmp = pd.read_csv('/content/drive/My Drive/Colab Notebooks/data/iris.csv',header=None).to_numpy()
# tmp = pd.read_csv('iris.csv',header=None).to_numpy()
X = tmp[:,0:-1]        # 150 x 4
y = tmp[:,-1]          # 150 x 1

First, partition the data into 80/20 using train_test_split

In [25]:
# 80/20 train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [26]:
# develop a Naive Bayes classifier
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_gnb_score = gnb.predict_proba(X_test)

Accuracy Score and Confusion Matrix

In [27]:
print("Naive Bayes score: ",format(gnb.score(X_test, y_test),".4f"))

Naive Bayes score:  0.9333


In [28]:
from sklearn.metrics import confusion_matrix
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print(confusion_matrix(y_test, y_pred))

[[14  0  0]
 [ 0 14  0]
 [ 0  3 14]]
