In [1]:
import numpy as np

# Distance matrix 
Dm = np.array([[0,1,4,5],[1,0,3,4],[4,3,0,1],[5,4,1,0]])
print('Distance matrix:\n', Dm)

Distance matrix:
 [[0 1 4 5]
 [1 0 3 4]
 [4 3 0 1]
 [5 4 1 0]]


In [12]:
# Similarity matrix
A = np.exp(-np.square(Dm))
np.set_printoptions(precision=3)
print('Similarity matrix:\n', A)

Similarity matrix:
 [[1.000e+00 3.679e-01 1.125e-07 1.389e-11]
 [3.679e-01 1.000e+00 1.234e-04 1.125e-07]
 [1.125e-07 1.234e-04 1.000e+00 3.679e-01]
 [1.389e-11 1.125e-07 3.679e-01 1.000e+00]]


In [13]:
# Degree matrix 
D = np.diag(np.sum(A,axis=1))
print('Degree matrix:\n', D)

Degree matrix:
 [[1.368 0.    0.    0.   ]
 [0.    1.368 0.    0.   ]
 [0.    0.    1.368 0.   ]
 [0.    0.    0.    1.368]]


In [14]:
# Laplacian matrix
L = D - A
print('Laplacian matrix:\n', L)

Laplacian matrix:
 [[ 3.679e-01 -3.679e-01 -1.125e-07 -1.389e-11]
 [-3.679e-01  3.680e-01 -1.234e-04 -1.125e-07]
 [-1.125e-07 -1.234e-04  3.680e-01 -3.679e-01]
 [-1.389e-11 -1.125e-07 -3.679e-01  3.679e-01]]


In [15]:
# Random Walk Laplacian matrix
Lrw = np.linalg.inv(D)@L
print('Random Walk Laplacian matrix:\n', Lrw)

Random Walk Laplacian matrix:
 [[ 2.689e-01 -2.689e-01 -8.227e-08 -1.015e-11]
 [-2.689e-01  2.690e-01 -9.021e-05 -8.226e-08]
 [-8.226e-08 -9.021e-05  2.690e-01 -2.689e-01]
 [-1.015e-11 -8.227e-08 -2.689e-01  2.689e-01]]


In [16]:
# Normalized Symmetric Laplacian matrix
Ls = np.sqrt(np.linalg.inv(D))@L@np.sqrt(np.linalg.inv(D))
print('Normalized Symmetric Laplacian matrix:\n',Ls)

Normalized Symmetric Laplacian matrix:
 [[ 2.689e-01 -2.689e-01 -8.227e-08 -1.015e-11]
 [-2.689e-01  2.690e-01 -9.021e-05 -8.227e-08]
 [-8.227e-08 -9.021e-05  2.690e-01 -2.689e-01]
 [-1.015e-11 -8.227e-08 -2.689e-01  2.689e-01]]


In [17]:
# Eigenvalue decompositions
W,V = np.linalg.eig(L)

# short eig vector (column vecotr) based on eig value
vecs = V[:,np.argsort(-W)]
vals = W[np.argsort(-W)]

print('Eigen value:\n', np.diag(vals))
print('Eigen vector:\n', vecs) 

Eigen value:
 [[7.359e-01 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 7.358e-01 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 1.236e-04 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 1.321e-16]]
Eigen vector:
 [[ 0.5  0.5  0.5 -0.5]
 [-0.5 -0.5  0.5 -0.5]
 [ 0.5 -0.5 -0.5 -0.5]
 [-0.5  0.5 -0.5 -0.5]]


In [18]:
# Kmeans algorithm of first two eigen vector
from sklearn.cluster import KMeans

c = 2
cluster = KMeans(n_clusters=c, random_state=0).fit(vecs[:,0:c])
print('Cluster index for each row in first c column eigen vectors: \n',cluster.labels_)

Cluster index for each row in first c column eigen vectors: 
 [0 1 1 0]
